type data {
	nodes: [Node]!
	links: [Link]!
}

type Node implements MooDElement{
	id: ID!
	name: String! @UI(name:"Name" default: "name")
	x: Int @UI(name:"X Coordinate")
	y: Int @UI(name:"Y Coordinate")
}

type Link implements MooDElement{
	id: ID!
	name: String! @UI(name:"Name" default: "name")
	source: EndPoint!
	target: EndPoint!
}

type EndPoint implements MooDElement{
	id: ID!
	name: String! @UI(name:"Name" default: "name")
}
