type Column{
    title: String!
    content: Any
    format: String
    editable: Boolean
}

type ColumnGroup{
    title: String!
    columns: [Column]
}
 
type data { 
    rows: [row!]!
    colorOption: String
} 
 
type row implements MooDElement { 
    columns: [Column]
    columnGroups: [ColumnGroup]
}
