export const processPhase = 'Process Phase'
export const processStep = 'Process Step'
export const decision = 'Decision'
export const decisionLarge = 'Decision Large'
export const offPageOutput = 'Off Page Output'
export const offPageInput = 'Off Page Input'
export const subProcess = 'Sub Process'
export const process = 'Process'
export const start = 'Start'
export const end = 'End'
export const document = 'Document / Form'
export const externalData = 'External Data'
export const database = 'Database / Application'
export const data = 'Data'
export const other = 'Other'
//
// BPMN Shapes
//
export const BPMNStartEvent = 'BPMN Start Event'
export const BPMNStartEventMessage = 'BPMN Start Event Message'
export const BPMNIntermediateEvent = 'BPMN Intermediate Event'
export const BPMNEndEvent = 'BPMN End Event'
export const BPMNExclusiveGateway = 'BPMN Exclusive Gateway'
export const BPMNParallelGateway = 'BPMN Parallel Gateway'
export const BPMNInclusiveGateway = 'BPMN Inclusive Gateway'
